name: vaporate
description: "A Flutter Point of Sales App for Vape Store."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  # UI / UX & Komponen Tambahan
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0
  fluttertoast: ^8.2.4
  intl: ^0.19.0
  shared_preferences: ^2.2.2
  provider: ^6.1.2

  # Animasi & Navigasi
  animations: ^2.0.11
  flutter_spinkit: ^5.2.0

  # HTTP / Simulasi API
  http: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
